// client/src/app/components/entities-sidebar/entities-sidebar.component.ts
// src/app/components/entities-sidebar/entities-sidebar.component.ts
import { Component, Input, OnChanges, SimpleChanges, ChangeDetectionStrategy, Output, EventEmitter } from '@angular/core'; // Added OnChanges, SimpleChanges, ChangeDetectionStrategy, Output, EventEmitter
import { CommonModule } from '@angular/common';
import { MatListModule } from '@angular/material/list';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatTooltipModule } from '@angular/material/tooltip'; // Added for tooltips

// Import necessary types
import { ExtractionResult, EntityOccurrence } from '../../core/models/types';

// Interface matching the React NestedEntity (can be moved to types.ts)
export interface NestedEntity {
  name: string;
  fullName: string; // Keep track of the full path, e.g., 'PatientInfo.Name'
  occurrences?: (EntityOccurrence & { id: string })[]; // Add ID here
  children?: Record<string, NestedEntity>;
  isExpanded?: boolean; // State for expand/collapse
}


@Component({
  selector: 'app-entities-sidebar',
  standalone: true,
  imports: [
    CommonModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatDividerModule,
    MatIconModule,
    MatButtonModule,
    MatTooltipModule // Added
  ],
  templateUrl: './entities-sidebar.component.html',
  styleUrls: ['./entities-sidebar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class EntitiesSidebarComponent implements OnChanges {

  @Input() extractionResult: ExtractionResult | null = null;
  @Input() isExtracting: boolean = false;

  // Output event for when an occurrence is clicked
  @Output() entityClicked = new EventEmitter<string>();

  // Processed nested structure for rendering
  nestedEntities: Record<string, NestedEntity> = {};
  hasEntities = false;

  constructor() { }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['extractionResult'] && this.extractionResult?.entities) {
        console.log("EntitiesSidebar: extractionResult changed, processing entities.");
        this.nestedEntities = this.buildNestedStructure(this.extractionResult.entities);
        this.hasEntities = Object.keys(this.nestedEntities).length > 0;
        console.log("Built structure:", this.nestedEntities);
    } else if (changes['extractionResult'] && !this.extractionResult) {
        // Clear if result is cleared
        this.nestedEntities = {};
        this.hasEntities = false;
    }
  }

  // --- Structure Building Logic (Adapted from React) ---
  private buildNestedStructure(entities: Record<string, EntityOccurrence[]>): Record<string, NestedEntity> {
    const structure: Record<string, NestedEntity> = {};

    Object.entries(entities).forEach(([fullName, occurrences]) => {
      const parts = fullName.split('.');
      let currentLevel = structure;
      let currentPath = '';

      // Ensure ID is added to each occurrence *before* assigning to structure
      const occurrencesWithId = occurrences.map((occ, index) => ({
        ...occ,
        id: `entity-${fullName}-${index}` // Consistent ID format
      }));

      parts.forEach((part, index) => {
        currentPath = currentPath ? `${currentPath}.${part}` : part;
        if (!currentLevel[part]) {
          // Initialize with potential children obj only if not the last part
          currentLevel[part] = {
             name: part,
             fullName: currentPath, // Store full path
             children: (index === parts.length - 1) ? undefined : {},
             isExpanded: true // Default to expanded
           };
        }

        if (index === parts.length - 1) {
          // Final entity name part: Assign occurrences
          currentLevel[part].occurrences = occurrencesWithId;
          // Ensure children is defined if it was already treated as parent
          if (!currentLevel[part].children) {
             currentLevel[part].children = {}; // Keep potentially expandable
          }
        } else {
           // Ensure children object exists for nesting
           if (!currentLevel[part].children) {
             currentLevel[part].children = {};
           }
           currentLevel = currentLevel[part].children!;
        }
      });
    });
    return structure;
  }

  // --- Template Helpers ---

   // Helper to get children as an array for *ngFor
   objectValues(obj: Record<string, NestedEntity> | undefined): NestedEntity[] {
       return obj ? Object.values(obj) : [];
   }

   // Toggle expand/collapse state
   toggleNode(node: NestedEntity): void {
       node.isExpanded = !node.isExpanded;
   }

   // Emit event when an occurrence is clicked
   onOccurrenceClick(occurrenceId: string): void {
       console.log("Entity occurrence clicked:", occurrenceId);
       this.entityClicked.emit(occurrenceId);
   }

   // Helper to check if a node can be expanded/collapsed
   canExpand(node: NestedEntity): boolean {
        const hasRealChildren = node.children && Object.keys(node.children).length > 0;
        const hasOccurrences = node.occurrences && node.occurrences.length > 0;
        return !!(hasRealChildren || hasOccurrences);
   }

    // Helper to determine if a node is purely structural (only contains other nodes)
   isStructuralOnly(node: NestedEntity): boolean {
       const hasRealChildren = node.children && Object.keys(node.children).length > 0;
       const hasOccurrences = node.occurrences && node.occurrences.length > 0;
       return !hasOccurrences && !!hasRealChildren;
   }

   // Render the value from an occurrence
   renderValue(value: any): string {
       if (Array.isArray(value)) { return value.join(', '); }
       if (typeof value === 'boolean') { return value ? 'Yes' : 'No'; }
       if (value === null || typeof value === 'undefined') { return 'N/A'; }
       return String(value);
   }

}
<div class="entities-container">
  <h3 class="sidebar-title">Extracted Entities</h3>
  <mat-divider></mat-divider>

  <div *ngIf="isExtracting" class="loading-indicator">
    <mat-progress-spinner diameter="30" mode="indeterminate"></mat-progress-spinner>
    <span>Loading Entities...</span>
  </div>

  <div *ngIf="!isExtracting && !hasEntities" class="no-entities-message">
    No entities extracted yet.
  </div>

  <mat-list *ngIf="!isExtracting && hasEntities" dense class="entity-list">
    <ng-container *ngFor="let entity of objectValues(nestedEntities)">
      <ng-container *ngTemplateOutlet="entityNode; context: { $implicit: entity, level: 0 }"></ng-container>
    </ng-container>
  </mat-list>

</div>

<ng-template #entityNode let-node let-level="level">
  <mat-list-item class="entity-item" [style.padding-left.px]="level * 16">
    <button mat-icon-button *ngIf="canExpand(node); else indentPlaceholder"
             (click)="toggleNode(node)"
             class="expand-button"
             [matTooltip]="node.isExpanded ? 'Collapse' : 'Expand'"
             aria-label="Toggle expansion">
       <mat-icon>{{ node.isExpanded ? 'expand_less' : 'expand_more' }}</mat-icon>
     </button>
     <ng-template #indentPlaceholder><div class="indent-placeholder"></div></ng-template>

    <span class="entity-name" [class.structural]="isStructuralOnly(node)">
      {{ node.name }}
      <span *ngIf="node.occurrences && !isStructuralOnly(node)" class="entity-count">
        ({{ node.occurrences.length }})
      </span>
    </span>
  </mat-list-item>

  <div *ngIf="node.isExpanded && canExpand(node)" class="node-content">
    <mat-list dense *ngIf="node.occurrences?.length">
      <mat-list-item *ngFor="let occ of node.occurrences"
                     class="occurrence-item"
                     [style.padding-left.px]="(level + 1) * 16"
                     (click)="onOccurrenceClick(occ.id)"
                     matTooltip="Click to scroll to text">
        <span class="occurrence-value">{{ renderValue(occ.value) }}</span>
      </mat-list-item>
    </mat-list>

    <ng-container *ngIf="node.children">
      <ng-container *ngFor="let child of objectValues(node.children)">
         <ng-container *ngTemplateOutlet="entityNode; context: { $implicit: child, level: level + 1 }"></ng-container>
      </ng-container>
    </ng-container>
  </div>
</ng-template>

// client/src/components/EntitiesSidebar.tsx
// src/components/EntitiesSidebar.tsx
import React, { useState, useMemo } from 'react'; // Added useMemo
import {
    Box,
    Typography,
    List,
    // ListItem, // No longer needed for the main item if using ListItemButton
    ListItemText,
    Collapse,
    IconButton,
    Divider,
    // Tooltip, // Removed as not used here
    CircularProgress,
    // Paper, // Removed as not used here
    ListItemButton // Keep this
} from '@mui/material';
import ExpandLess from '@mui/icons-material/ExpandLess';
import ExpandMore from '@mui/icons-material/ExpandMore';
import { ExtractionResult, EntityOccurrence, NestedEntity } from '../types';

interface EntitiesSidebarProps {
    extractionResult: ExtractionResult | null;
    isExtracting: boolean;
    onEntityClick: (entityId: string) => void;
}

const renderValue = (value: any): string => {
    if (Array.isArray(value)) { return value.join(', '); }
    if (typeof value === 'boolean') { return value ? 'Yes' : 'No'; }
    if (value === null || typeof value === 'undefined') { return 'N/A'; }
    return String(value);
};

const buildNestedStructure = (entities: Record<string, EntityOccurrence[]>): Record<string, NestedEntity> => {
    const structure: Record<string, NestedEntity> = {};

    Object.entries(entities).forEach(([fullName, occurrences]) => {
        const parts = fullName.split('.');
        let currentLevel = structure;
        let currentPath = '';

         // Ensure ID is added to each occurrence *before* assigning to structure
        const occurrencesWithId = occurrences.map((occ, index) => ({
            ...occ,
            id: `entity-${fullName}-${index}`
        }));


        parts.forEach((part, index) => {
            currentPath = currentPath ? `${currentPath}.${part}` : part;
            if (!currentLevel[part]) {
                // Initialize with potential children obj only if not the last part
                currentLevel[part] = { name: part, children: (index === parts.length - 1) ? undefined : {} };
            }

            if (index === parts.length - 1) {
                // Final entity name part: Assign occurrences
                currentLevel[part].occurrences = occurrencesWithId;
                 // Ensure children is defined if it was already treated as parent
                 if (!currentLevel[part].children) {
                    currentLevel[part].children = {}; // Keep expandable for consistency if needed
                 }
            } else {
                 // Ensure children object exists for nesting
                 if (!currentLevel[part].children) {
                    currentLevel[part].children = {};
                 }
                currentLevel = currentLevel[part].children!;
            }
        });
    });
    return structure;
};

// Recursive component to render nested entities
const NestedEntityItem: React.FC<{
    entityData: NestedEntity;
    level: number;
    onEntityClick: (entityId: string) => void;
}> = ({entityData, level, onEntityClick }) => {
    const [open, setOpen] = useState(true); // Keep default as open for now
    // Check for actual nested children *data*, not just the empty {} placeholder
    const hasRealChildren = entityData.children && Object.values(entityData.children).some(child => child.name);
    const hasOccurrences = entityData.occurrences && entityData.occurrences.length > 0;
    const canExpand = hasRealChildren || hasOccurrences; // Can expand if it has children OR direct occurrences to show

    const handleClick = () => {
        if (canExpand) { // Only toggle if there's something to expand/collapse
             setOpen(!open);
        }
    };

    // Determine if this item is purely structural (only holds other nested items)
    const isStructuralOnly = !hasOccurrences && hasRealChildren;

    return (
        <>
             {/* Use ListItemButton for the main clickable/expandable item */}
            <ListItemButton
                onClick={handleClick}
                sx={{ pl: level * 2, py: 0.3 }} // Indentation + padding
                disabled={!canExpand} // Disable click if nothing to show/hide
            >
                <ListItemText
                    primary={
                        <Typography variant="body2" sx={{ fontWeight: isStructuralOnly ? 'normal' : 'bold' }}>
                            {entityData.name}
                             {/* Show count only if it has direct occurrences and IS NOT purely structural */}
                             {hasOccurrences && !isStructuralOnly && ` (${entityData.occurrences!.length})`}
                        </Typography>
                    }
                    disableTypography
                    sx={{ my: 0, mr: 1 }} // Add margin if there's an icon
                />
                {/* Show expand icon only if it has something to expand */}
                 {canExpand ? (
                     <IconButton size="small" edge="end" aria-label="expand">
                        {open ? <ExpandLess /> : <ExpandMore />}
                    </IconButton>
                 ) : <Box sx={{ width: 34 }}/> /* Placeholder to keep alignment */}
            </ListItemButton>

            {/* Collapsible section for children AND occurrences */}
            <Collapse in={open} timeout="auto" unmountOnExit>
                <List component="div" disablePadding>
                     {/* Render direct occurrences if they exist (indented further) */}
                    {hasOccurrences && entityData.occurrences!.map((occ) => (
                        <ListItemButton
                            key={occ.id}
                            onClick={() => occ.id && onEntityClick(occ.id)} // Click occurrence scrolls
                            sx={{ pl: (level + 1) * 2, py: 0.2 }} // Indent occurrences
                        >
                            <ListItemText
                                primary={
                                    <Typography component="span" variant="caption">
                                        {renderValue(occ.value)}
                                    </Typography>
                                }
                                disableTypography
                                sx={{ my: 0 }}
                            />
                        </ListItemButton>
                    ))}

                    {/* Recursively render children */}
                    {hasRealChildren && Object.entries(entityData.children!).map(([childKey, childData]) => (
                         // Ensure we only render children that have a name (aren't just placeholders)
                         childData.name ? (
                             <NestedEntityItem
                                key={childKey}
                                entityData={childData}
                                level={level + 1}
                                onEntityClick={onEntityClick}
                            />
                         ) : null
                    ))}
                 </List>
            </Collapse>
        </>
    );
};


function EntitiesSidebar({ extractionResult, isExtracting, onEntityClick }: EntitiesSidebarProps) {

    const nestedEntities = useMemo(() => {
        if (!extractionResult || !extractionResult.entities) return {};
        return buildNestedStructure(extractionResult.entities);
    }, [extractionResult]);

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', height: '100%', pt: 6 }}>
             <Typography variant="h6" gutterBottom component="div" sx={{ px: 2, pb: 0, mt: -1 }}>
                 Extracted Entities
             </Typography>
            <Divider sx={{ mb: 1 }} />

            {isExtracting && (
                <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', p: 3 }}>
                    <CircularProgress size={24} />
                    <Typography variant="body2" sx={{ ml: 2 }}>Loading Entities...</Typography>
                </Box>
            )}

            {!isExtracting && (!extractionResult || Object.keys(extractionResult.entities).length === 0) && (
                <Typography variant="body2" color="text.secondary" sx={{ p: 2 }}>
                    No entities extracted yet.
                </Typography>
            )}

            <Box sx={{ flexGrow: 1, overflowY: 'auto' }}>
                {!isExtracting && extractionResult && Object.keys(nestedEntities).length > 0 && (
                    <List dense disablePadding sx={{ px: 1 }}>
                        {Object.entries(nestedEntities).map(([key, data]) => (
                            <NestedEntityItem
                                key={key}
                                entityData={data}
                                level={0}
                                onEntityClick={onEntityClick}
                            />
                        ))}
                    </List>
                )}
            </Box>
        </Box>
    );
}

export default EntitiesSidebar;
