// client/src/app/components/results-display/results-display.component.ts
// src/app/components/results-display/results-display.component.ts
import { Component, Input, ChangeDetectionStrategy, OnChanges, SimpleChanges, ViewChild, ElementRef, Renderer2, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatCardModule } from '@angular/material/card';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatIconModule } from '@angular/material/icon';

// Import necessary types
import { ExtractionResult, EntityOccurrence, ScrollTarget } from '../../core/models/types';

// Define structure for processed segments to render
interface HighlightedSegment {
  text: string;
  isEntityValue: boolean;
  isEntityContext: boolean;
  entityType?: string; // e.g., 'PatientName', 'Medication'
  entityId?: string; // Unique ID for scrolling, e.g., "entity-PatientName-0"
  backgroundColor?: string; // For entity value
  borderColor?: string; // For entity context
}

@Component({
  selector: 'app-results-display',
  standalone: true,
  imports: [
    CommonModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatExpansionModule,
    MatIconModule
  ],
  templateUrl: './results-display.component.html',
  styleUrls: ['./results-display.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ResultsDisplayComponent implements OnChanges, AfterViewInit { // Implement OnChanges

  @Input() extractionResult: ExtractionResult | null = null;
  @Input() isExtracting: boolean = false;
  @Input() extractionError: string | null = null;
  @Input() scrollToTarget: ScrollTarget | null = null; // For scroll handling

  @ViewChild('highlightedTextContainer') highlightedTextContainerRef!: ElementRef<HTMLDivElement>; // Reference to the container for scrolling

  // Property to hold the processed segments for rendering
  highlightedSegments: HighlightedSegment[] = [];

  // Define colors for highlighting
  private highlightColors = ['#a2d2ff', '#ffafcc', '#bde0fe', '#ffc8dd', '#cdb4db', '#ff9573', '#f7b57e', '#bfb636', '#076912', '#98f5e1'];
  private activeHighlightId: string | null = null;
  private highlightTimeout: any = null; // For managing scroll timeout

  constructor(private renderer: Renderer2) { }

  ngAfterViewInit(): void {
    if (this.scrollToTarget) {
      this.executeScroll(this.scrollToTarget.id);
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    let processNeeded = false;
    // Check if extractionResult input has changed and has a valid value
    if (changes['extractionResult']) {
      processNeeded = true;
      if (!this.extractionResult) {
        this.highlightedSegments = [];
        processNeeded = false;
      }
    }

    if (processNeeded && this.extractionResult?.text) {
      this.processHighlights(this.extractionResult);
    }

    // --- Handle Scrolling ---
    if (changes['scrollToTarget'] && this.scrollToTarget) {
      console.log("ResultsDisplay: scrollToTarget changed:", this.scrollToTarget);
      // Ensure the container is ready before attempting to find the element
      // Use setTimeout to allow the DOM to update after ngOnChanges completes
      setTimeout(() => {
        if (this.highlightedTextContainerRef?.nativeElement) { // Check if container exists
          this.executeScroll(this.scrollToTarget!.id);
        } else {
          console.warn("Container ref not ready for scrolling yet.");
          // ngAfterViewInit will handle scrolling if target was set early
        }
      }, 0);
    }
  }

  private executeScroll(targetId: string): void {
    const element = document.getElementById(targetId); // Find the <mark> element by ID
    if (element) {
        console.log(`Scrolling to element ID: ${targetId}`);
        element.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });

        // --- Temporary Highlighting ---
        // Clear previous timeout and styles if any
        if (this.highlightTimeout) {
            clearTimeout(this.highlightTimeout);
        }
        // Remove previous active class if applicable
        if (this.activeHighlightId) {
           const previousElement = document.getElementById(this.activeHighlightId);
           if (previousElement) {
             this.renderer.removeClass(previousElement, 'active-highlight');
           }
        }

        // Apply new active class and set timeout to remove it
        this.activeHighlightId = targetId;
        this.renderer.addClass(element, 'active-highlight');

        this.highlightTimeout = setTimeout(() => {
            this.renderer.removeClass(element, 'active-highlight');
            this.activeHighlightId = null;
            this.highlightTimeout = null;
             // Optional: Emit scrollComplete event here if needed
        }, 1500); // Highlight duration

    } else {
        console.warn(`Element with ID "${targetId}" not found for scrolling.`);
        // Optional: Emit scrollComplete event here even if not found
    }
  }

  private processHighlights(result: ExtractionResult): void {
    const text = result.text;
    const entities = result.entities;
    const segments: HighlightedSegment[] = [];

    if (!text || !entities) {
        this.highlightedSegments = [{ text: text || '', isEntityValue: false, isEntityContext: false }];
        return;
    }

    // 1. Collect all highlight details (value, context, color, id)
    // This structure helps manage overlapping regions later
     interface HighlightInfo {
       valueStart: number; valueEnd: number;
       contextStart: number; contextEnd: number;
       type: string; color: string; id: string;
     }
     const highlights: HighlightInfo[] = [];
     let colorIndex = 0;

     Object.entries(entities).forEach(([entityName, occurrences]) => {
       const color = this.highlightColors[colorIndex % this.highlightColors.length];
       colorIndex++;
       occurrences.forEach((occ, occIndex) => {
         // Basic validation of positions
         if (occ.position && typeof occ.position.start === 'number' && typeof occ.position.end === 'number' &&
             occ.context?.position && typeof occ.context.position.start === 'number' && typeof occ.context.position.end === 'number')
         {
             const uniqueId = `entity-${entityName}-${occIndex}`; // Consistent ID format
             highlights.push({
               valueStart: occ.position.start,
               valueEnd: occ.position.end,
               contextStart: occ.context.position.start,
               contextEnd: occ.context.position.end,
               type: entityName,
               color,
               id: uniqueId,
             });
         } else {
             console.warn(`Invalid position/context data for entity ${entityName} occurrence ${occIndex}:`, occ);
         }
       });
     });

    // 2. Create sorted list of unique start/end points
    const points = new Set<number>([0]); // Start with 0
    highlights.forEach(h => {
      points.add(h.valueStart); points.add(h.valueEnd);
      points.add(h.contextStart); points.add(h.contextEnd);
    });
    points.add(text.length); // Ensure the end of the text is included
    const sortedPoints = Array.from(points).sort((a, b) => a - b).filter((p, i, arr) => i === 0 || p > arr[i - 1]); // Ensure points are unique and sorted

    // 3. Build segments by iterating through points
    for (let i = 0; i < sortedPoints.length - 1; i++) {
        const start = sortedPoints[i];
        const end = sortedPoints[i + 1];

        if (start >= end) continue; // Skip zero-length or invalid segments

        const segmentText = text.substring(start, end);
        if (!segmentText) continue; // Skip empty segments

        const segmentMid = start + (end - start) / 2;

        let isValue = false;
        let isContext = false;
        let valueColor = '';
        let contextColor = '';
        let entityId = '';
        let entityType = '';

        // Check which highlights cover the *middle* of this segment
        // Prioritize value highlights over context if they overlap exactly
        let bestMatch: HighlightInfo | null = null;
        for (const h of highlights) {
             if (segmentMid > h.valueStart && segmentMid < h.valueEnd) {
                 isValue = true;
                 valueColor = h.color;
                 entityId = h.id; // ID belongs to the value
                 entityType = h.type;
                 bestMatch = h; // Found a value match, store it
                 break; // Prioritize value
             }
        }

        // If not a value segment, check for context
         if (!isValue) {
             for (const h of highlights) {
                  // Check if segmentMid falls within a context range
                 if (segmentMid > h.contextStart && segmentMid < h.contextEnd) {
                      // Only consider this context if it doesn't contain the value highlight we might have found earlier
                      // (This handles cases where context fully contains the value)
                      if (!bestMatch || !(h.contextStart <= bestMatch.valueStart && h.contextEnd >= bestMatch.valueEnd)) {
                         isContext = true;
                         contextColor = h.color;
                         // Note: context doesn't get the primary ID in this model
                         entityType = h.type; // Still useful to know the type
                         break; // Found the first context match
                      }
                 }
             }
         }

        segments.push({
            text: segmentText,
            isEntityValue: isValue,
            isEntityContext: isContext && !isValue, // Only context if NOT also value
            entityId: isValue ? entityId : undefined, // ID only on the value segment
            entityType: entityType || undefined,
            backgroundColor: isValue ? valueColor : undefined,
            borderColor: isContext && !isValue ? contextColor : undefined
        });
    }

    this.highlightedSegments = segments;
  }
}
<div class="results-container">
  <div *ngIf="isExtracting" class="loading-overlay">
    <mat-progress-spinner mode="indeterminate" diameter="50"></mat-progress-spinner>
    <p>Processing...</p>
  </div>

  <mat-expansion-panel *ngIf="extractionError && !isExtracting" class="error-panel" [expanded]="true">
      <mat-expansion-panel-header>
          <mat-panel-title>
              <mat-icon color="warn">error_outline</mat-icon> Extraction Error
          </mat-panel-title>
      </mat-expansion-panel-header>
      <p>{{ extractionError }}</p>
  </mat-expansion-panel>


  <mat-card *ngIf="!isExtracting && !extractionError && extractionResult?.text" class="results-card">
    <mat-card-header>
      <mat-card-title>Extracted Text</mat-card-title>
    </mat-card-header>
    <mat-card-content>
       <div #highlightedTextContainer class="highlighted-text-container">
         <ng-container *ngFor="let segment of highlightedSegments">
            <mark *ngIf="segment.isEntityValue"
                  [id]="segment.entityId"
                  [title]="segment.entityType"
                  [style.backgroundColor]="segment.backgroundColor"
                  class="entity-value">
                {{segment.text}}
            </mark>
            <span *ngIf="segment.isEntityContext"
                  [style.border]="'1.5px dashed ' + segment.borderColor"
                  [title]="segment.entityType + ' (Context)'"
                  class="entity-context">
                {{segment.text}}
            </span>
            <span *ngIf="!segment.isEntityValue && !segment.isEntityContext">
                {{segment.text}}
            </span>
         </ng-container>
       </div>
    </mat-card-content>
  </mat-card>

  <mat-card *ngIf="!isExtracting && !extractionError && !extractionResult?.text" class="no-results-card">
    <mat-card-content>
        <p class="placeholder-text">No results to display. Upload a file and click Extract.</p>
    </mat-card-content>
  </mat-card>
</div>

// client/src/components/ResultsDisplay.tsx
// src/components/ResultsDisplay.tsx
import React, { useRef, useState, useEffect } from 'react'; // Keep necessary React imports for HighlightedText
import { Box, Typography } from '@mui/material';
import { ExtractionResult, EntityOccurrence, ScrollTarget } from '../types'; // Import needed types
import DisplayStateIndicator from './DisplayStateIndicator';
// Import the wrapper component
import { TextInteractionWrapper } from './TextInteractionWrapper';
// Assuming AnnotationPopup is used internally by TextInteractionWrapper now

// --- Define Props ---
interface ResultsDisplayProps {
    extractionResult: ExtractionResult | null;
    isExtracting: boolean;
    extractionError: string | null;
    scrollToTarget: ScrollTarget | null;
    availableEntityNames: string[]; // <-- Accept entity names
    onAddAnnotation: (value: string, start: number, end: number, entityName: string) => void; // <-- Accept handler
}

// --- Define HighlightedText Component Props ---
// (Moved interface definition closer to component)
interface HighlightedTextProps {
    text: string;
    entities: Record<string, EntityOccurrence[]>;
    scrollToTarget: ScrollTarget | null;
}

// --- HighlightedText Component (Implementation Detail) ---
// This component now focuses solely on rendering the text with highlights
const HighlightedText: React.FC<HighlightedTextProps> = React.memo(({
    text,
    entities,
    scrollToTarget
}) => {
    const containerRef = useRef<HTMLDivElement>(null); // Ref for the scroll container DIV
    const [activeContextId, setActiveContextId] = useState<string | null>(null); // For temporary context highlight

    // --- Effect for scrolling to entity ---
    useEffect(() => {
        if (scrollToTarget?.id && containerRef.current) {
            // Use timeout to ensure element exists after potential re-render
            setTimeout(() => {
                const element = document.getElementById(scrollToTarget.id);
                if (element) {
                    element.scrollIntoView({ behavior: 'smooth', block: 'center' });

                    // Highlight context temporarily
                    const contextElementId = `context-${scrollToTarget.id}`;
                    setActiveContextId(contextElementId);

                    // Highlight the element itself temporarily
                    element.style.transition = 'outline 0.1s ease-in-out, box-shadow 0.1s ease-in-out';
                    element.style.outline = '2px solid red';
                    element.style.boxShadow = '0 0 5px red';

                    const timer = setTimeout(() => {
                        setActiveContextId(null); // Clear context highlight state
                        if(element) { // Check if element still exists
                           element.style.outline = 'none';
                           element.style.boxShadow = 'none';
                        }
                    }, 1500); // Duration of element highlight

                    // Cleanup timeout on unmount or if target changes
                    return () => clearTimeout(timer);
                } else {
                     console.warn(`Element with ID "${scrollToTarget.id}" not found for scrolling.`);
                }
            }, 0); // Timeout 0 allows DOM to update first
        }
    }, [scrollToTarget]); // Re-run if scrollToTarget changes


    // --- Generate Highlighted Output (Memoize if complex) ---
    // This calculation can be memoized using useMemo if performance becomes an issue
    const output: React.ReactNode[] = (() => {
        // Interface for internal highlight processing
        interface HighlightInfo {
            valueStart: number; valueEnd: number;
            contextStart: number; contextEnd: number;
            type: string; color: string; id: string;
        }

        const highlights: HighlightInfo[] = [];
        // Consistent color palette
        const colors = ['#a2d2ff', '#ffafcc', '#bde0fe', '#ffc8dd', '#cdb4db', '#ffddd2', '#fde4cf', '#fbf8cc', '#b9fbc0', '#98f5e1'];
        let colorIndex = 0;

        // Flatten entities into highlight list
        Object.entries(entities || {}).forEach(([entityName, occurrences]) => {
            const color = colors[colorIndex % colors.length];
            colorIndex++;
            occurrences.forEach((occ) => { // No index needed if ID comes from backend/hook
                // Ensure ID exists (should come from backend or addAnnotation)
                if (!occ.id) {
                    console.warn("Occurrence missing ID:", occ);
                    return; // Skip occurrences without IDs
                }
                highlights.push({
                    valueStart: occ.position.start, valueEnd: occ.position.end,
                    contextStart: occ.context.position.start, contextEnd: occ.context.position.end,
                    type: entityName, color, id: occ.id,
                });
            });
        });

        // Get all unique boundary points
        const points = new Set<number>([0, text.length]); // Include start and end of text
        highlights.forEach(h => {
            points.add(h.valueStart); points.add(h.valueEnd);
            points.add(h.contextStart); points.add(h.contextEnd);
        });
        const sortedPoints = Array.from(points).sort((a, b) => a - b);

        // Build segments
        const segments: React.ReactNode[] = [];
        let currentPos = 0;
        sortedPoints.forEach((point) => {
            if (point > currentPos && point <= text.length) { // Ensure point is within bounds
                const segmentText = text.substring(currentPos, point);
                if (!segmentText) { // Skip empty segments
                    currentPos = point;
                    return;
                }

                const segmentMid = currentPos + (segmentText.length / 2);
                let bestMatch: HighlightInfo | null = null;
                let isValue = false;

                // Find the most specific highlight covering this segment's midpoint
                for (const h of highlights) {
                    if (segmentMid > h.valueStart && segmentMid <= h.valueEnd) {
                        bestMatch = h;
                        isValue = true;
                        break; // Value match takes precedence
                    }
                    if (!isValue && segmentMid > h.contextStart && segmentMid <= h.contextEnd) {
                         // Smallest context wins if multiple contexts overlap
                        if (!bestMatch || (h.contextEnd - h.contextStart < bestMatch.contextEnd - bestMatch.contextStart)) {
                            bestMatch = h;
                        }
                    }
                }

                const elementKey = `seg-${currentPos}-${point}`;
                if (bestMatch) {
                    const style: React.CSSProperties = { padding: '1px 0px', margin: '0', borderRadius: '3px', display: 'inline' };
                    const Tag = isValue ? 'mark' : 'span';
                    const finalId = isValue ? bestMatch.id : undefined;
                    const contextElementId = `context-${bestMatch.id}`;
                    const segmentIsContext = (bestMatch && segmentMid > bestMatch.contextStart && segmentMid <= bestMatch.contextEnd);

                    if (isValue) {
                        style.backgroundColor = bestMatch.color;
                        style.cursor = 'pointer'; // Indicate clickability (for scrolling)
                    }
                    if (segmentIsContext) {
                        style.border = `1.5px dashed ${bestMatch.color}80`; // Dashed border for context (with transparency)
                        if (activeContextId === contextElementId) {
                            style.border = `1.5px solid ${bestMatch.color}`; // Solid border when active
                            style.boxShadow = `0 0 3px ${bestMatch.color}`;
                             // Slightly enhance background when context is active
                            style.backgroundColor = isValue ? bestMatch.color : `${bestMatch.color}40`; // Keep value color or add context bg tint
                        }
                    }
                     // Add transition for smoother context highlighting
                    style.transition = 'border 0.2s ease-in-out, background-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out';

                    segments.push(
                        <Tag key={elementKey} id={finalId} style={style} title={isValue ? bestMatch.type : undefined}>
                            {segmentText}
                        </Tag>
                    );
                } else {
                    // Non-highlighted text
                    segments.push(<span key={elementKey}>{segmentText}</span>);
                }
            }
            currentPos = point;
        });

        return segments;
    })(); // Immediately invoke the function to get the result

    // The outer div has the ref for scrollIntoView calculations
    return (
        <div ref={containerRef}>
            <Typography component="div" sx={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', lineHeight: 1.8 }}>
                {output}
            </Typography>
        </div>
    );
});
// Add display name for React DevTools
HighlightedText.displayName = 'HighlightedText';


// --- Main ResultsDisplay Component ---
function ResultsDisplay({
    extractionResult,
    isExtracting,
    extractionError,
    scrollToTarget,
    availableEntityNames, // Accept props
    onAddAnnotation     // Accept props
}: ResultsDisplayProps) {

    return (
        // Outer container Box
        <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
            {/* Shows Loading/Error/No Results states */}
            <DisplayStateIndicator
                isExtracting={isExtracting}
                extractionError={extractionError}
                hasResultText={!!extractionResult?.text}
            />

            {/* Wrapper handles text interaction (selection, popup) */}
            <TextInteractionWrapper
                 fullText={extractionResult?.text}
                 availableEntityNames={availableEntityNames}
                 onAddAnnotation={onAddAnnotation}
                 disabled={isExtracting || !!extractionError} // Disable interaction when busy/error
            >
                {/* Render HighlightedText only when there's text */}
                {extractionResult?.text && (
                     <HighlightedText
                         text={extractionResult.text}
                         // Ensure entities is passed, default to empty object if null/undefined
                         entities={extractionResult.entities || {}}
                         scrollToTarget={scrollToTarget}
                    />
                 )}
                 {/* Show placeholder if no text but not extracting/error */}
                 {!isExtracting && !extractionError && !extractionResult?.text && (
                     <Typography sx={{ p: 2, color: 'text.secondary', textAlign: 'center', mt: 4 }}>
                         Upload a file and extract entities to see results.
                     </Typography>
                 )}
            </TextInteractionWrapper>
        </Box>
    );
}

export default ResultsDisplay;
